---
title: "kmer-similarity"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(dplyr)
library(dtplyr)
library(reshape2)
library(stringr)
library(parallel)
library(ggplot2)
library(dbscan)
```

Load similarity scores

```{r}
scores = fread("data/alignment_matrix/vdjam.txt")
```

Generate 3-mers

```{r}
aas = unique(scores$aa.1)
kmers = expand.grid(aa.1 = aas,
                    aa.2 = aas,
                    aa.3 = aas) %>%
  mutate(kmer = paste0(aa.1,aa.2,aa.3)) %>%
  melt(id.vars="kmer") %>%
  mutate(pos = str_split_fixed(as.character(variable), fixed("."), 2)[,2], aa = value) %>%
  select(kmer, pos, aa) %>%
  as.data.table
```

Distance based on alignment

```{r}
compute_dists = function(k) {
  kmers %>% 
    filter(kmer == k) %>%
    mutate(kmer.1 = kmer, aa.1 = aa) %>% 
    select(-kmer, -aa) %>%
    merge(kmers %>%
            mutate(kmer.2 = kmer, aa.2 = aa) %>% 
            select(-kmer, -aa), by = "pos") %>%
    merge(scores, by = c("aa.1", "aa.2")) %>%
    group_by(kmer.1, kmer.2) %>%
    summarise(score = sum(score)) %>%
    ungroup
}

compute_dists("AAA") %>% str
```

Pairwise distances

```{r}
kmer_dists = kmers %>% .$kmer %>% unique %>% as.list %>%
  mclapply(compute_dists, mc.cores = 80) %>%
  rbindlist
```

Distribution of scores

```{r}
kmer_dists %>%
  mutate(score.i = as.integer(round(score*10))) %>%
  filter(kmer.1 >= kmer.2) %>%
  group_by(score.i) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = score.i, y = count)) +
  geom_bar(stat = "identity")
```

Convert to matrix

```{r}
mat_kmer_dists = kmer_dists %>%
  filter(!grepl("C", paste(kmer.1, kmer.2))) %>%
  dcast(kmer.1 ~ kmer.2, value.var = "score")
rownames(mat_kmer_dists) = mat_kmer_dists$kmer.1
mat_kmer_dists$kmer.1 = NULL
mat_kmer_dists = as.matrix(mat_kmer_dists)
```

Convert to distance measure

```{r}
mat_kmer_dists.d = as.dist(pmin(2^(-mat_kmer_dists), 10))
summary(mat_kmer_dists.d)
```

Clusters

```{r}
hcl = hclust(mat_kmer_dists.d)
plot(hcl, hang = 0)
```

Principal components (very time-consuming)

```{r}
pc = prcomp(mat_kmer_dists, scale = T)
plot(pc)
biplot(pc)
```

Write results

```{r}
pc$sdev[1:54] # next < 1, followed by ~0
dt.pc = data.table(kmer = rownames(pc$x)) %>%
  cbind(pc$x[,1:54])
fwrite(dt.pc, "kmer-blosum-pc.txt", sep = "\t")
```


```
M = replicate(nrow(mat_kmer_dists), mat_kmer_dists[,1]^2) +
  t(replicate(nrow(mat_kmer_dists), mat_kmer_dists[1,]^2)) -
  mat_kmer_dists^2
M = M / 2

ed = eigen(M, T)
```









