---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(dplyr)
library(dtplyr)
library(reshape2)
library(stringr)
library(parallel)
library(ggplot2)
library(dbscan)
library(NMF)
```

Aux. functions for kmerizaiton

```{r}
flatten_aas = function(seqs) {
  rbindlist(mclapply(strsplit(unique(seqs), ""),
                           function(x) data.table(seq = paste0(x, collapse = ""),
                                                  ind = 1:length(x),
                                                  aa = x), mc.cores = 80))
}

get_kmers = function(seq, n) {
  kmers = ""
  for (i in 1:n) {
    kmers = paste0(kmers, seq[i:length(seq)])
  }
  kmers[1:(length(seq)-n+1)]
}

get_kmers_c = function(seq, n) {
  get_kmers(strsplit(seq, "")[[1]], n)
}

get_kmers_c("CASSLAPGATNEKLFF", 5)

get_kmers_d = function(seqs, n) {
  rbindlist(mclapply(strsplit(seqs, ""),
                     function(x) data.table(seq = paste0(x, collapse = ""), 
                                            kmer = get_kmers(x, n), 
                                            index=1:(length(x)-n+1)),
                     mc.cores = 60))
}

get_kmers_d(c("CASSLAPGATNEKLFF",
              "CAVRLNTGKFF", 
              "CILDDNDMRF"), 5)
```

Get kmers for vdjdb

```{r}
vdjdb.seqs = fread("../vdjdb.txt") %>%
  filter(!startsWith(antigen.epitope, "ELA"),
         !startsWith(antigen.epitope, "NLV")) %>% # no CMV/ELA
  select(cdr3, antigen.epitope) %>%
  unique 

dt.epi.count = vdjdb.seqs %>%
  group_by(antigen.epitope) %>%
  summarise(count = n())

good_epi = dt.epi.count %>%
  filter(count >= 100) %>%
  .$antigen.epitope

vdjdb.seqs = vdjdb.seqs %>%
  filter(antigen.epitope %in% good_epi)

vdjdb.kmers = vdjdb.seqs %>%
  .$cdr3 %>%
  unique %>%
  get_kmers_d(3) %>%
  filter(index >= 4 | index <= nchar(seq) - 4) %>%
  mutate(cdr3 = seq) %>%
  select(-seq) %>%
  merge(vdjdb.seqs, by = "cdr3")
```

Transform to vectors

```{r}
kmer_vec = fread("kmer-vdjam-vec-2.txt") %>%
  melt %>% as.data.table

vdjdb.kmers.vec = vdjdb.kmers %>%
  merge(kmer_vec, by="kmer", allow.cartesian=T) %>%
  group_by(antigen.epitope, cdr3, variable) %>%
  summarise(value = sum(value))
```


```{r}
m.vdjdb.kmers.vec = vdjdb.kmers.vec %>%
  filter(startsWith(antigen.epitope, "GIL") |
         startsWith(antigen.epitope, "GLC")) %>%
  dcast(antigen.epitope + cdr3 ~ variable)

m2.vdjdb.kmers.vec = m.vdjdb.kmers.vec %>%
  select(-antigen.epitope, -cdr3) %>%
  as.matrix
  
aheatmap(m2.vdjdb.kmers.vec, 
         annRow = m.vdjdb.kmers.vec$antigen.epitope,
         hclustfun = "ward",
         distfun = "pearson")
```

```{r}
m.vdjdb.kmers.vec = vdjdb.kmers.vec %>%
  dcast(antigen.epitope + cdr3 ~ variable)

m2.vdjdb.kmers.vec = m.vdjdb.kmers.vec %>%
  select(-antigen.epitope, -cdr3) %>%
  as.matrix %>%
  scale
  
aheatmap(pmin(pmax(m2.vdjdb.kmers.vec, -5), 5), #Colv = NA, 
         annRow = m.vdjdb.kmers.vec$antigen.epitope)

#ggplot(m.vdjdb.kmers.vec, aes(x = PC1, y=PC2, color = antigen.epitope)) +
#  geom_point()
```
